# Generated by Django 3.2.7 on 2022-06-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_numericalparams'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('interval', 'user')},
        ),
    ]
